from collections import namedtuple

pcfg = namedtuple('pcfg','lo, hi, nbins, log, profile, name')

config = {
    'pt'          : pcfg(      0,     30,   30,  True, False, 'p_T [GeV]'),
    'eta'         : pcfg(-3.1415, 3.1415,   40, False, False, 'eta'),
    'phi'         : pcfg(-3.1415, 3.1415,   40, False, False, 'phi'),
    'mass'        : pcfg(  -0.05,   0.05,   40,  True, False, 'mass'),
    'dxy'         : pcfg(    -25,     25,   40,  True, False, 'd_{xy} [mm]'),
    'dxyErr'      : pcfg(      0,     20,   40,  True, False, 'd_{xy} Error [mm]'),
    'dz'          : pcfg(    -20,     20,   40, False, False, 'd_{z} [mm]'),
    'dzErr'       : pcfg(      0,     20,   40,  True, False, 'd_{z} Error [mm]'),
    'fBrem'       : pcfg(   -0.2,      0,   40, False, False, 'fBrem'),
    'ip3d'        : pcfg(      0,     35,   40,  True, False, 'ip3d'),
    'sip3d'       : pcfg(      0,   2750,   40,  True, False, 'sip3d'),
    'pfRelIso'    : pcfg(      0,    3.5,   40,  True, False, 'pfRelIso'),
    'pfvaId'      : pcfg(   19.9,     20,   40,  True, False, 'pfvaId'),
    'trkRelIso'   : pcfg(      0,    200,   40,  True, False, 'trkRelIso'),
    'vx'          : pcfg(    -20,     20,   40,  True, False, 'vx'),
    'vy'          : pcfg(    -20,     20,   40,  True, False, 'vy'),
    'vz'          : pcfg(    -45,     45,   40,  True, False, 'vz'),
    'charge'      : pcfg(     -1,      1,   40, False, False, 'charge'),
    'pdgId'       : pcfg(    -11,     11,   40, False, False, 'pdgId'),
    'genPartIdx'  : pcfg(     -1,   -0.5,   40, False, False, 'genPartIdx'),
    'GenPartFlav' : pcfg(      0,      6,   40, False, False, 'GenPartFlav'),
    'mvaId'       : pcfg(   None,   None, None, False,  True, 'mvaId'),
    'ptBiased'    : pcfg(   None,   None, None, False,  True, 'ptBiased'),
    'unBiased'    : pcfg(   None,   None, None, False,  True, 'unBiased'),
}

truth_pl = {
            "pt"     : True,
            "eta"    : True,
            "phi"    : True,
            "mass"   : True,
            "status" : True,
            "mother" : True,
            "pdgId"  : True,
}
reco_pl = {
            "pt"          : True,
            "phi"         : True,
            "eta"         : True,
            "dxy"         : True,
            "dxyErr"      : True,
            "dz"          : True,
            "dzErr"       : True,
            "fBrem"       : True,
            "ip3d"        : True,
            "mvaId"       : True,
            "pfRelIso"    : True,
            "pfvaId"      : False,
            "ptBiased"    : True,
            "sip3d"       : True,
            "trkRelIso"   : True,
            "unBiased"    : True,
            "vx"          : True,
            "vy"          : True,
            "vz"          : True,
            "charge"      : False,
            "pdgId"       : False,
            "genPartIdx"  : False,
            "GenPartFlav" : False,
            "sxy"         : (lambda x : x['dxy'] / x['dxyErr']),
            "sz"          : (lambda x : x['dz'] / x['dzErr']),
}
